openshift/cluster-authentication-operator

- pkg/operator2/configmap.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
This PR makes the route that we create be honored in our OAuth configuration in order for OSIN to be reachable.
I also did a check of the Route object we create according to https://docs.okd.io/latest/architecture/networking/routes.html. The behavior of the Route is described in the commit message of the second commit.
> Honor route name assigned to our service in our config

- pkg/operator2/configsync.go
- pkg/operator2/helpers.go
- pkg/operator2/operator.go
We still need to add code to handle the syncData redeployment case.
@openshift/sig-auth
> Fix informers to correctly watch secrets and configmaps

- pkg/operator2/configsync.go
Grabs identity providers' configmaps and secrets from the
top-level config and stores their mapping to volumes/volumeMounts
so that these can later be added to the deployment running OSIN
> Get secret/configmaps information from config for all IdPs

- pkg/operator/operator.go
- pkg/operator/starter.go
the kubeapiserver API is moving and the name is changing. This updates to handle both changes.  Not super gracefully, but the whole thing is temporary.
/assign @enj
> handle kubeapiserver api movement

- pkg/boilerplate/controller/controller.go
- pkg/boilerplate/controller/die.go
- pkg/boilerplate/controller/informer.go
- pkg/boilerplate/controller/option.go
- pkg/boilerplate/operator/option.go
- pkg/operator/operator.go
- pkg/operator2/operator.go
Enhance controller boilerplate
1. Be strict on how long we wait for caches to sync
2. Add support for opting out of informer cache sync
3. Add support for initial event to prime sync loop
---
console and kube api server operator informers: skip cache sync
The CRDs backing these resources may not exist.  We do not want to wedge the operator on them.
---
/assign @mrogers950
> console and kube api server operator informers: skip cache sync

- pkg/operator2/console.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
This change allows the console to use Javascript to interact with
the OAuth server.  This is required for JS to easily perform certain
actions such as logout.  Note that the console was always in the
allowed CORS list for all 3.x releases.
/assign @stlaz
> Add CORS support for console public hostname

- pkg/operator2/console.go
It is currently not required so let us remove it.
> Remove CORS for the console

- manifests/cluster-authentication-operator_05_deploy.yaml
There is no need to run 3 replicas of the operator.
> Run single replica of authentication operator

- pkg/operator2/configsync.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
Redeploys the osin server if any of the configMaps and secrets in the top-level config changed.
Manually tested.
> Redeploy when a secret/configmap from top-level config changes

- pkg/operator2/idp.go
The conversion of the LDAP IdP config type to the internal one
was missing the "Attributes" attribute.
Manually tested.
> idp: fix LDAP identity provider

- pkg/operator2/idp.go
Hopefully last missing attribute.
This time I've gone through all of the IdPs in the file and checked with openshift/api that all the attributes from configv1 are taken into account for them, I did not find anything else to be missing.
> idp: add missing Teams attribute in GH IdP

- pkg/operator2/deployment.go
Run the oauth-server on master nodes only. Also, only run 1 replica - masters don't have enough resources for more and almost all of the other critical components are set to 1.
https://jira.coreos.com/browse/AUTH-191
> chore(pkg/operator2/deployment): schedule on master nodes

- manifests/cluster-authentication-operator_03_cm.yaml
- manifests/cluster-authentication-operator_05_deploy.yaml
This change lowers the default log level of the operator to 2.  This prevents leader election spam (we still want leader election even with one replica to make sure we behave nicely during an upgrade).
It also disables delegated authentication and authorization as the operator does not expose any HTTP endpoints.
@openshift/sig-auth
> Reduce log spam and turn off unneeded delegation

- pkg/operator2/operator.go
- pkg/operator2/operatorclient.go
- pkg/operator2/starter.go
- pkg/operator2/status.go
Adds a `library-go` controller for status changes and also
adds status failure reporting in auth operator Sync() if an error
occured in the lower level machinery.
Based on current `library-go` and `kube-apiserver-operator` code.
> Add status updates

- pkg/operator2/ca.go
- pkg/operator2/configmap.go
- pkg/operator2/operator.go
- pkg/operator2/starter.go
Adds redeployment of the osin pods when the pod template or SSCS serving cert/key change
> Add redeploy on serving cert and operator pod template change

- pkg/operator2/operator.go
This prevents us from deadlocking forever on a resource that will never be created.
This manifests in the logs as:
failed with: secrets "v4-0-config-system-serving-cert" not found
@stlaz this was caused by #75 and broke the console queue.
@spadgett
> Create the service before waiting for serving certs

- pkg/operator2/configsync.go
For some reason I did not think I'd need the dots replace when I started doing it and later I forgot to add it.
I did not test this yet, I bricked my cluster before I get to do it.
> fix template synced secret names

- pkg/operator2/console.go
- pkg/operator2/infrastructure.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
This change moves to the OsinServerConfig struct.  This removes our dependence on the KubeAPIServerConfig.
It also wires the apiServerURL from the top level infrastructure config.  This allows us to provide the correct login url for the token request endpoint.
@openshift/sig-auth 
/hold
Blocked on https://github.com/openshift/origin/pull/21987
> Move to OsinServerConfig

- pkg/operator2/deployment.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/starter.go
This change moves us to a passthrough route that can support the mTLS requirements of the request header identity provider.
1. Sync router certs from openshift-config-managed to openshift-authentication namespace
2. Mount (copied) router certs into deployment
3. SNI: wire each key, value pair in router certs secret to a domain and the mount path for the combined TLS cert and key data.
@openshift/sig-auth @Miciah @ironcladlou @knobunc
> Move to a passthrough route to support mTLS

- manifests/cluster-authentication-operator_05_deploy.yaml
- pkg/operator2/deployment.go
Operators deployed via the CVO should have system-cluster-critical priority.
Operators that use shas for images should use IfNotPresent pull policy.
> Update operator and operand manifests for priority and imagePolicy

- pkg/operator2/deployment.go
Bug 1683991: Run 2 replicas of oauth server
Cause: default deployment was running only 1 replica
Consequence: oauth server didn't have the availability guarantee
required
Fix: change deployment to run 2 replicas
Result: better availability of the oauth server
> fix(operator2/deployment): run 2 replicas for redundancy

- pkg/operator2/configsync.go
- pkg/operator2/idp.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
This change fixes how we handle OAuth templates (we correctly build the secret name and path).
As part of the fix, end-user provided names are not used in any way to determine the destination secret or path.
AUTH-223
This was tested with htpasswd, github and the login template.
/assign @stlaz 
cc @barleyer
> Correctly handle OAuth templates

- manifests/cluster-authentication-operator_05_deploy.yaml
- manifests/cluster-authentication-operator_06_clusteroperator.yaml
- pkg/operator2/operator.go
- pkg/operator2/starter.go
- pkg/operator2/status.go
Adds the version we get from the deployment to the clusteroperator
and authetnication.operator statuses. Also delays the authentication.operator
status updates to the end of Sync() so that we don't stomp on our own foot
should we want to be calling either of the set*Status() methods.
Also adds the clusteroperator to manifests.
> Add version to (cluster)operator status

- manifests/cluster-authentication-operator_02_config.crd.yaml
@enj  I used `library-go/cmd/crd-schema-gen` to generate the CRD validation
operator api has been updated recently, so had to bump deps to get the fancy crd-validation-gen.  however, that bump caused issues in auth-operator that I did not want to fix in this PR, so I  deleted the bump commits, will address those issues here: https://github.com/openshift/cluster-authentication-operator/pull/97
> Bug 1677587: Add openAPIV3Schema validation to operator config

- pkg/operator2/deployment.go
- pkg/operator2/operator.go
logLevel: treat empty string to mean the default
We do not have strong validation for the logLevel field today.  Yet
we want to make sure OAuth failures are apparent in the OAuth
server's logs.  Thus for now we will treat empty string as the same
as Normal.  This translates to glog level 2 which captures OAuth
failures.
---
redeploy on operatorConfig.spec changes
Since we no longer track the resource version of operatorConfig in
the OAuth server's deployment, a change to operatorConfig.spec will
not cause ApplyDeployment to issue an update.  Because we track the
generation in operatorConfig.status, we can compare it to determine
if a force redeploy is required.  This is effectively the same as if
we used the operatorConfig.generation as its …
> redeploy on operatorConfig.spec changes

- pkg/operator2/idp.go
- pkg/operator2/oauth.go
- pkg/operator2/transport.go
- vendor/github.com/openshift/api/config/v1/types_oauth.go
Make default grant method impossible to use
Set the default grant method to deny so that all OAuth clients are
forced to set it explicitly.  The validation in origin will be
updated to mark grant method as required.
---
Infer challenge and login based on IDP
These fields offer a level of flexibility that is not particularly
useful to admins.  In reality all IDPs have a correct configuration
for these fields based on the feature set that the IDP supports.  We
should avoid asking users questions that we already know the answer
to.
---
Add issuer to OpenIDIdentityProvider
This change adds an issuer field which can be used to perform
discovery via the /.well-known/openid-configuration endpoint.  This …
> Tighten APIs

- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/starter.go
This change builds a transport using the router-certs secret
provided by the ingress operator (this secret is expected to
contain both the CA and cert data).  If no CA data is found, it is
assumed that the admin has replaced the default wildcard certificate
with a globally valid cert.  To handle this, we fallback to the
default transport.
Remove use of rest.Config in favor of building custom transports.
This prevents us from emitting our service account token
unnecessarily.
Properly check well-known (we incorrectly skipped it).
Generally improve our readiness error reporting.
Bug 1691488
@openshift/sig-auth
> Bug 1691488: Fix route healthz to tolerate custom wildcard certs

- manifests/cluster-authentication-operator_03_version-mapping.yaml
- manifests/cluster-authentication-operator_05_deploy.yaml
- pkg/operator2/deployment.go
- pkg/operator2/operator.go
This change updates the operator deployment to include the operand
version as an environment variable.  Since we encode the operator
deployment RV into the operand deployment, we correctly gate on
changing the version until the new version has rolled out.
The VersionForOperand function uses a config map with a version to
image mapping to determine the operand version.  It does this by
reversing the mapping (image to version).  This has a serious flaw
in that it assumes that all versions point to distinct images
(which is not the case since an image may not change during a
release).  Since map iteration order is undefined, this can lead to
the operand version flapping back and forth as the reversed map
changes based on which image value was written last.
Remove version-mapping config map …
> Bug 1695244: Correctly determine operand version

- pkg/operator2/starter.go
Do not use WithTweakListOptions with the config informer as top
level configs are all called "cluster" whereas our cluster operator
instance is called "authentication" (there is no OR support).
> Fix config informer to not use WithTweakListOptions

- pkg/operator2/operator.go
- pkg/operator2/status.go
Currently we always set Available=False when we set Progressing=True and Available=True/Progressing=False.  This PR fine-tunes those to set independently when appropriate.
> Bug 1694173: Improve status reporting

- pkg/operator2/deployment.go
- pkg/operator2/operator.go
Tie the operand's image pull policy to the operator's image pull
policy.  This makes it easy during development to change both the
operator and operand's image once the CVO is configured to no longer
manage the operator.
> Make it easier to control operand image pull policy

- pkg/operator2/auth.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/starter.go
This allows us to treat the empty value as a valid state.
> Handle defaulting of top level config

- README.md
- pkg/operator2/oauth.go
This allows the mapping method value to be left unset and defaulted.
This is primarily for consistency with the rest of the config APIs as we likely never change the default to anything else.
@stlaz you validation needs to tolerate this (I do not know if it does or not).
@spadgett @benjaminapetersen FYI so that you can remove the mapping method from the console.
> Default mapping method to claim

- manifests/02_config.cr.yaml
- pkg/operator2/starter.go
Change the reference to EnsureOperatorConfigExists helper, which is being removed, to instead create the operator resource with the other manifests and tag it to be managed by the CVO
> Use CVO for management of operator config resource

- pkg/boilerplate/operator/option.go
Cause: operator used an emoji as the operator informer key
Consequence: error logs contain emoji character, confusing users
Fix: change key to more boring but informative value
Result: errors from operator controller shows "authentication-operator"
instead of emoji
> Bug 1694818: remove emoji from event logs

- manifests/00_namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
> Add node-selector annotation to namespace

- pkg/operator2/idp.go
- pkg/operator2/operator.go
- pkg/operator2/transport.go
Confirm that all KAS have observed our OAuth metadata
This change updates the well known check to verify that all masters
have observed our metadata config.  The IP of the masters is
determined by their endpoints resource.
This prevents a race in CI where the install will report completed
and start running tests that fail with an "Unauthorized" error.
This error occurs because a request was sent to a master that had
not observed our OAuth metadata and thus had the logic the honors
OAuth tokens disabled.
Bug 1694878
---
SNI: Set ServerName to KAS for well-known
---
Logs from testing:
```
I0426 17:58:26.235995       1 round_trippers.go:438] GET …
```
> Bug 1694878: Confirm that all KAS have observed our OAuth metadata

- manifests/03_configmap.yaml
Enable Auth for metrics endpoint for cluster-authentication-operator.
By default delegated authentication and authorization are enabled.
Currently the configmap explicitly disables delegated authentication
and authorization.
Remove the override to enable delegated authentication
and authorization.
Testing:
- Make sure that /metrics endpoint is not accessible for an
unauthenticated user.
If I access the /metrics endpoint using curl as shown below I get the
following 403 error
curl -k https://$(kubectl get service metrics -o json | jq -r .spec.clusterIP)/metrics
"message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
"reason": "Forbidden",
- I checked 'prometheus-k8s-openshift-monitoring', looks like all
'AuthenticationOperator2_*' metrics are collected after …
> Bug 1703502: Enable Auth for metrics endpoint

- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
- manifests/04_roles.yaml
- manifests/05_serviceaccount.yaml
- manifests/08_clusteroperator.yaml
- pkg/operator2/ingress.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
We need a permanently stable issuer URL for the OAuth server - both
in terms of the OAuth spec and so that OAuth callbacks from OAuth
IDPs continue to work indefinitely (we have no way to reconcile the
external IDP on a change).
oauth-openshift is the shortest namespaced value we can use (we do
not want to use a value that a customer may want to use).  This is a
best effort attempt to make the external API "nice" to use.
To keep things consistent, everything that was previously exposed as
"integrated-oauth-server" is now "oauth-openshift" (this does make
us slightly inconsistent with the top level Authentication config
and the binary of the OAuth server - we can at least update the
latter in the future for consistency).
Bug 1706894
> Bug 1706894: Make oauth-openshift.<ingress_domain> the permanent issuer of the OAuth server

- manifests/07_deployment.yaml
- pkg/operator2/deployment.go
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
> Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down

- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/status.go
This change is meant as a starting point for more nuanced handling of the degraded condition.  We will likely need to add more conditions as the sync loop is broken apart.
xref: #141
> Bug 1725935: Split handling of degraded across multiple conditions

- pkg/operator2/operator.go
- pkg/operator2/starter.go
@sallyom or @stlaz - easy review.
> Make it clear that we do not support the removed state

- Makefile
- pkg/operator2/branding.go
- pkg/operator2/configsync.go
- pkg/operator2/configsync_test.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/resourceversion.go
- pkg/operator2/resourceversion_test.go
This patch makes two primary changes:
1. Generically track resource versions:
We depend on the following state:
- The operator deployment itself
- The authentications.operator.openshift.io resource
- Config maps and secrets that are owned by the operator
- The current observed (CLI) config (stored in a config map)
- Config maps and secrets that are synced from openshift-config
Thus by tracking the:
- operator deployment resource version
- authentications.operator.openshift.io generation
- resource version of config maps and secrets with config prefix
we can guarantee that we redeploy when our state has changed.
2. Correct race between config sync loop and resource syncer
The code in master incorrectly assumed that the calls to List
contained all of the config maps and secrets that were …
> Bug 1733336: Correct race between config sync loop and resource syncer

- pkg/operator2/deployment.go
- pkg/operator2/operator.go
- pkg/operator2/proxy.go
The Proxy object specifies certain http-proxy related environmnent
variables that we need setting for the operand's cotainer.
/cc @sttts @enj
> deployment: add env vars from the Proxy object

- manifests/07_deployment.yaml
uses https://github.com/openshift/cluster-version-operator/pull/224
/assign @stlaz @enj
> ask for proxy env vars to be injected for OIDC communication

- pkg/operator2/operator.go
- pkg/operator2/status.go
> Bug 1740121: Prevent global sync error degraded status flapping

- Makefile
- pkg/operator2/branding.go
- pkg/operator2/configsync.go
- pkg/operator2/configsync_test.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/resourceversion.go
- pkg/operator2/resourceversion_test.go
This patch makes two primary changes:
1. Generically track resource versions:
We depend on the following state:
- The operator deployment itself
- The authentications.operator.openshift.io resource
- Config maps and secrets that are owned by the operator
- The current observed (CLI) config (stored in a config map)
- Config maps and secrets that are synced from openshift-config
Thus by tracking the:
- operator deployment resource version
- authentications.operator.openshift.io generation
- resource version of config maps and secrets with config prefix
we can guarantee that we redeploy when our state has changed.
2. Correct race between config sync loop and resource syncer
The code in master incorrectly assumed that the calls to List
contained all of the config maps and secrets that were …
> Bug 1733978: Correct race between config sync loop and resource syncer [4.1]

- manifests/03_configmap.yaml
- manifests/07_deployment.yaml
- pkg/operator2/deployment.go
- pkg/operator2/idp.go
- pkg/operator2/operator.go
> Inject payload's system store with proxy CA when specified

- pkg/operator2/route.go
The ingress operator performs no validation on the certs it is given
by the user.  Thus it can easily pass us nonsensical data.  We guard
against it and provide useful error messages.
This change also detects if the ingress operator ever wedges and
fails to keep the router-certs updated with the correct certs on an
ingress.config domain plus cert change.
> Bug 1740366: Add strict validation for router certs

- pkg/operator2/deployment.go
- pkg/operator2/operator.go
- pkg/operator2/resourceversion.go
- pkg/operator2/resourceversion_test.go
When the operator is set in debug mode, this makes it much easier to understand what change is causing redeployments of the OAuth server.
The log statements look like:
```
tracked resource versions: configmaps:v4-0-config-system-cliconfig:12119,...,proxy:cluster:435,...,secrets:v4-0-config-system-session:12093
```
> Log inputs to operator.openshift.io/rvs-hash

- pkg/operator2/route.go
When multiple ingress domains are configured, the router-certs
secret will have a key for each domain.  When we build the named
certificates slice to pass to the OAuth server via its CLI config,
we need to guarantee that the output is stable.  Otherwise the OAuth
server will be consistently redeployed since the config hash will be
different each time.
Since router-certs is a map, we need to iterate over it in a
deterministic manner to make the output stable.
> Bug 1747480: Make SNI output stable when multiple ingress domains are configured

- pkg/operator2/deployment.go
- pkg/operator2/operator.go
This change prevents the OAuth server's pods from hanging indefinitely on upgrade when the trusted-ca-bundle does not exist.
> Explicitly mark trusted-ca-bundle optional for OAuth server

- pkg/operator2/apiserver.go
- pkg/operator2/auth.go
- pkg/operator2/branding.go
- pkg/operator2/ca.go
- pkg/operator2/configmap.go
- pkg/operator2/configsync.go
- pkg/operator2/configsync_test.go
- pkg/operator2/console.go
- pkg/operator2/deployment.go
- pkg/operator2/idp.go
- pkg/operator2/infrastructure.go
- pkg/operator2/ingress.go
- pkg/operator2/oauth.go
- pkg/operator2/oauthclients.go
- pkg/operator2/operator.go
- pkg/operator2/operatorclient.go
- pkg/operator2/proxy.go
- pkg/operator2/resourceversion.go
- pkg/operator2/resourceversion_test.go
- pkg/operator2/route.go
- pkg/operator2/route_test.go
- pkg/operator2/secret.go
- pkg/operator2/secret_test.go
- pkg/operator2/service.go
- pkg/operator2/starter.go
Using consts everywhere makes it impossible to grep the code for strings. These strings will never change and if they do it will be when we will rewrite this operator.
/cc @enj 
/cc @deads2k
> Inline all consts

- manifests/03_configmap.yaml
- manifests/03_operand_trusted_ca.yaml
- manifests/03_operator_trusted_ca.yaml
It seems that during upgrade, CVO might be applying whole files,
not just objects, which would cause it to remove the contents of
trusted-ca-bundle configmap in loop with CNO.
> manifests: split configmaps

- pkg/operator2/route.go
- pkg/operator2/route_test.go
It seems that new fields with non-nil default values were added to
routes, specifically .spec.to.weigh and .spec.wildcardPolicy.
Since we do not expect them in the route, it gets stomped on
all of the time.
-----
We may want to find a better way to ensure the substantial fields are configured the way we need them.
cc @mfojtik @enj
> Bug 1753886: Don't stomp on our own route

- Makefile
- README.md
updates Makefile to allow a custom image registry like so:
`make IMAGE_REGISTRY=quay.io/sallyom images`
updates README to link common operator/operand info
> update README and Makefile

- manifests/07_deployment.yaml
- manifests/08_clusteroperator.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See openshift/cluster-version-operator#252
> Add manifest annotations for hosted deployment exclusions

- manifests/07_deployment.yaml
- manifests/08_clusteroperator.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See openshift/cluster-version-operator#252
> Bug 1776421: Add manifest annotations for hosted deployment exclusions (4.3)

- manifests/03_configmap.yaml
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
This PR includes the changes necessary to work in a cluster with IPv6 enabled (either IPv6-only or IPv4 and IPv6).
"bindNetwork: tcp" will always do the right thing, based on whether IPv4/IPv6/both are enabled.
One other fix was needed to more carefully join a host and port number together.
> Bug 1788135: Fix IPv6 Support

- manifests/03_openshift_service_ca.yaml
- manifests/07_deployment.yaml
- pkg/controller/ingressstate/ingress_state_controller.go
- pkg/controller/ingressstate/ingress_state_controller_test.go
- pkg/operator2/service.go
- pkg/operator2/starter.go
Failed health checks will result in degraded operator conditions. This is intended to allow differentiation between endpoint health (a responsibility of this operator) and route health (a responsibility of the network operator).
Forked from #211
Co-authored-by: Maru Newby <marun@redhat.com>
> Enable health checking of oauth-server endpoints

- pkg/operator2/starter.go
The old resync period was 20 min, far too long to reliably check the .well-known endpoint.
> Bug 1809193: Resync auth operator informer every 30 sec to tighten sync loop for .well-known check

- bindata/oauth-openshift/deployment.yaml
- pkg/operator2/assets/bindata.go
When a pod is marked deleted, endpoints are updated instantly and
propagate to load balancers, routers, and nodes. A component that
wishes to remain available during upgrades must wait longer than
the default propagation interval for these changes to avoid having
requests delivered to pods that are shutting down.
Change the oauth server to wait 25s before terminating the serving
process and up to 40s on the node to ensure all front ends have
time to drain. The minimum interval here is how long an average
connection can take behind the router to drain, once new connections
stop getting created. I.e.
wait = time to propagate endpoints (5s) +
time for router reload (5s) +
time for longest request to finish (15s)
= 25s
This should result in the oauth route not reporting any downtime
during …
> The oauth server should wait until it is out of rotation to shut down

- pkg/controller/ingressstate/ingress_state_controller.go
- pkg/controller/ingressstate/ingress_state_controller_test.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/status.go
Previously the primary auth controller set all condition types when performing an update. With the addition of the ingress state and router certs controllers, this behavior resulted in status message
flapping as the primary controller raced with the new controllers. The fix is having the primary controller avoid setting the condition types managed by the other controllers.
/cc @stlaz @mfojtik
> Bug 1817748: Fix ingress state condition flapping

- .gitignore
- Makefile
- go.mod
- go.sum
- vendor/github.com/openshift/build-machinery-go/go.mod
- vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
- vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
- vendor/modules.txt
**NOTE** https://github.com/openshift/build-machinery-go/pull/14 needs to merge before this PR.
Once telepresence has been installed (see the run-telepresence.sh script for instructions), `make telepresence` will replace the operator's pod with a local process that has access to the same environment as the pod. This can speed up development since iteration doesn't require cycles of image build/push/pull. See https://telepresence.io for more details.
> Bug 1834852: Add make target to run operator with telepresence

- bindata/oauth-openshift/deployment.yaml
- manifests/07_deployment.yaml
- pkg/operator2/assets/bindata.go
We are doing root write with the copying of the trusted cert bundle
so we unfortunately need the FS to be writable.
The SA running the pod has broad privileges and if there's a more
restrictive SCC with higher priority than what anyuid has, this
would make the container fail to start as it would choose to
default to non-writable root system.
> Bug 1824800: explicitly set oauth-server container's root file system to writable

- Makefile
- pkg/operator2/configobservation/routersecret/observe_router_secret.go
This fixed a small-ish bug in the router-secrets observer:
when running the repository-local e2e test, one could observe the following:
```
E0605 10:01:58.163141       1 base_controller.go:180] "ConfigObserver" controller failed to sync "key", err: .servingInfo.namedCertificates accessor error: <nil> is of the type <nil>, expected []interface{}
I0605 10:01:58.164534       1 event.go:278] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"b7da59af-4c37-4be6-b870-c4810f2cd833", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ObservedConfigChanged' Writing updated observed config:   map[string]interface{}{
"oauthServer": map[string]interface{}{
"corsAllowedOrigins": …
```
> router-secrets: set named certificates to empty array instead of nil when none found

- pkg/operator2/operator.go
The function landed in a14c2f00d1 (#77).  It had an unused `route` argument then, and seems to have never consumed the argument since.
> pkg/operator2/operator: Drop unused 'route' argument from oauthClientsReady

- pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
- pkg/controllers/configobservation/oauth/template_conversions.go
- pkg/operator/starter.go
As `v4-0-config-system-console-config` config map is not mounted in oauth-server pod, maybe using a resource sync controller to synchronize with `console-config` config map from `openshift-config-managed` is not fully beneficial. Instead, the observer could directly watch for any changes in `console-config`. This would reduce the number of `DELETE` requests made to kube-apiserver.
> Bug 1853278: observe console-config config map without using a resource sync controller.

- pkg/controllers/common/conditions.go
- pkg/controllers/deployment/deployment_controller.go
- pkg/controllers/ingressstate/ingress_state_controller.go
- pkg/controllers/metadata/metadata_controller.go
- pkg/controllers/payload/payload_config_controller.go
- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/controllers/serviceca/service_ca_controller.go
- pkg/controllers/targetversion/target_version_controller.go
Further simplifies the syncs among controllers
/assign @mfojtik
> controllers: abstract status setting logic

- pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
- pkg/controllers/configobservation/interfaces.go
- pkg/controllers/configobservation/oauth/observe_idps.go
- pkg/controllers/configobservation/oauth/observe_idps_test.go
- pkg/controllers/configobservation/oauth/observe_templates.go
- pkg/controllers/configobservation/oauth/observe_templates_test.go
- pkg/controllers/configobservation/oauth/observe_tokenconfig.go
- pkg/controllers/configobservation/oauth/observe_tokenconfig_test.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/oauth/observe_tokenconfig.go
- vendor/modules.txt
Bumps openshift/api and openshift/library-go and reuses config observer from https://github.com/openshift/library-go/pull/816
> Use config observer from library-go

- pkg/controllers/readiness/unsupported_override.go
- pkg/controllers/readiness/wellknown_ready_controller.go
CI for aws serial https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.6/1291399473506816000 shows this very clearly.
The connection checker doesn't show an outage because when the endpoint is removed it adapts smoothly.  However, the etcd test runs a port-forward `cmd := exec.CommandContext(ctx, "oc", "port-forward", "service/etcd", ":2379", "-n", "openshift-etcd")`.  The port forward sometimes gets unlucky and chooses a host which is going to rollout.
This prevents that from happening using a pattern similar to etcd to allow the unsafe choice of non-HA configuration which can be inconsistent.
> Bug 1841372: prevent Available=true until all kube-apiservers have restarted

- pkg/operator/apiservices/sync_take_over_apiservices_oauth_apiserver.go
it turns out that `!converged` will also be reported during the oauth apiserver installation
> logs when the encryption deployer hasn't yet converged

- pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
Add client side timeout to not wait ~2mins to report a failure. Request is expected to be served within 5 seconds now. Also add the flag to get proxy configuration from the environment. This flag should resolve the issues we are seeing in proxy environments.
> Bug 1867908: add connection timeouts and proxy from env to http client

- pkg/controllers/deployment/deployment_controller.go
- pkg/controllers/endpointaccessible/endpoint_accessible_controller.go
- pkg/controllers/endpointaccessible/endpoint_accessible_controller_test.go
- pkg/controllers/endpointaccessible/endpoints_accessible.go
- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/controllers/targetversion/target_version_controller.go
- pkg/operator/starter.go
Since the CVO treats availability as "past the post", this cause a blip which disturbs the installation flow.
> authentication operator is marked available because the deployment is missing

- manifests/07_deployment.yaml
- pkg/operator2/deployment.go
We are doing root write with the copying of the trusted cert bundle
so we unfortunately need the FS to be writable.
The SA running the pod has broad privileges and if there's a more
restrictive SCC with higher priority than what anyuid has, this
would make the container fail to start as it would choose to
default to non-writable root system.
-------------
I accidentally removed the original branch for https://github.com/openshift/cluster-authentication-operator/pull/287
> [4.3] Bug 1842465: explicitly set operator's and operand's container's root file system to writable

- pkg/controllers/deployment/deployment_controller.go
In case there was an error during `ApplyDeployment`, the deployment would be `nil`, the controller would panic never to recover again.
/assign @mfojtik
> Bug 1874713: deployment: don't panic when applying deployment fails

- pkg/controllers/routercerts/controller.go
- pkg/controllers/routercerts/controller_test.go
- pkg/operator/starter.go
Sometimes, the CA cert does not seem to appear in the routercerts secret. We should have always trusted the default ingress cert for router certs, adding that here.
/assign @deads2k 
/cc @Miciah
> Bug 1866818: routercerts: always trust the default ingress ca

- manifests/07_deployment.yaml
Rename the operator container to allow for more reasonable debugging.
> Bug 1876858: manifests: rename operator container to be more descriptive

- pkg/controllers/configobservation/oauth/idp_conversions.go
Some OIDCs return HTML page when they don't support password grants.
> Bug 1877803: don't error out on non-json output of password grant attempt

- pkg/controllers/ingressnodesavailable/OWNERS
- pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
- pkg/operator/starter.go
The purpose of this controller is to check whether nodes are available to schedule ingress pods (which require workload schedulable nodes).
Not having ingress available is very common failure case for authentication but it lacks a good signal (from ingress operator) and the authentication operator is not available resulting in longer bug triage and red herring.
This controller handle also case when masters are schedulable, however the workers schedulable is best-effort as there could be taints and toleration that can take effect and cause router pods to not be able to schedule.
> Bug 1878776: ingressnodesavailable: add controller that checks if router can schedule pods

- pkg/operator/starter.go
The annotation `oauth-apiserver.openshift.io/secure-token-storage: true` set on the config/v1 apiserver object make oauth-apiserver deeply log oauth tokens, noth access and authorize. 
This requires that there are no non-sha256 tokens in the system. For 4.6 installs this is guaranteed. 
After downgrade to 4.5 there is a controller removing the annotation. 
After upgrade from 4.5, the annotation is not set. The admin can set it manually after having made sure that no non-sha256 tokens exist.
For upgrade to 4.7, non-sha256 tokens must not exist. If they do, the upgrade will be blocked by the auth operator (to be implemented).
> Bug 1878648: oauth-apiserver: audit log oauthaccesstokens if fresh 4.6 install

- manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
- manifests/00_namespace.yaml
- manifests/02_config.cr.yaml
- manifests/02_service.yaml
- manifests/03_configmap.yaml
- manifests/03_openshift_service_ca.yaml
- manifests/03_operator_trusted_ca.yaml
- manifests/04_roles.yaml
- manifests/05_serviceaccount.yaml
- manifests/07_deployment.yaml
- manifests/08_clusteroperator.yaml
Cluster profiles are a way to support different deployment models for OpenShift clusters. A profile is an identifier that the Cluster Version Operator uses to determine which manifests to apply. Operators can be excluded completely or can have different manifests for each supported profile.
To support above, a deployment model in which not all operators rendered by the CVO by default is needed. The use case includes IBM Public Cloud, in which a hosted control plane is used. Potentially it can also be used for Code Ready Containers.
The following annotation may be used to include manifests for a given profile:
```
include.release.openshift.io/[identifier]=true
```
This would make the CVO render this manifest only when CLUSTER_PROFILE=[identifier] has been specified.
This PR is just a …
> bug 1871890: add current profile annotations to CVO manifests

- go.mod
- go.sum
- pkg/controllers/common/route.go
- pkg/controllers/deployment/deployment_controller.go
- pkg/controllers/metadata/metadata_controller.go
- test/library/waits.go
- vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
- vendor/modules.txt
Using the helper from openshift/library-go#911 to centralize some route handling and error message generation.
Generated with:
```console
$ emacs pkg/... # everything in the diff
$ go get github.com/openshift/library-go@f360b9835cc8815eccc26cb52dafe05d3cbb3e93
go: github.com/openshift/library-go f360b9835cc8815eccc26cb52dafe05d3cbb3e93 => v0.0.0-20201006230840-f360b9835cc8
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```
using:
```console
$ go version
go version go1.15.2 linux/amd64
```
> pkg/controllers: Use library-go's IngressURI helper

- pkg/controllers/deployment/deployment_controller.go
When authentication.operator observedGeneration and readyReplicas
get set before the observed deployment's generation, the last element
would have never gotten set and the ApplyDeployment function would have
kept reporting deployment update event endlessly.
> Bug 1891758: deployment: update event spam

- pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
- pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller_test.go
- pkg/operator/starter.go
/hold for unit tests
This adds code to honor the node placement on the ingress controller https://github.com/openshift/cluster-ingress-operator/blob/c6491b2c5d04f81aa36b3c409de1c49a5c228ae3/pkg/operator/controller/ingress/deployment.go#L342-L347
/assign @mfojtik
> bug 1893386: update ingress node available to handle custom placement

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
While the current log directory permissions are restrictive and correct,
the file permissions are too permissive and it raises flags on
evaluations of the deployment. Let's instead change the permissions to
0600 which is more appropriate for these types of logs.
> Restrict log permissions

- pkg/controllers/common/route.go
Typos from 6d95db740f (#299).  Fixed with:
```console
$ sed -i 's/successfull /successful /' $(git grep -l 'successfull ')
```
> pkg/controllers/common: Fix "successfull" -> "successful" typos

- Makefile
- go.mod
- go.sum
- pkg/operator/encryptionprovider/encryptionprovider_test.go
- pkg/operator/encryptionprovider/encyrptionprovider.go
- pkg/operator/starter.go
- test/e2e-encryption-perf/encryption_perf_test.go
- test/e2e-encryption/encryption_test.go
- test/e2e-encryption/oauthhelpers.go
- test/library/encryption/assertion.go
- test/library/encryption/helpers.go
- vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/statemachine/transition.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
- vendor/modules.txt
updates the encryption provider so that CAO can start to manage its own encryption configuration.
> starts to manage the encryption configuration

- manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
- manifests/00_namespace.yaml
- manifests/02_config.cr.yaml
- manifests/02_service.yaml
- manifests/03_configmap.yaml
- manifests/03_openshift_service_ca.yaml
- manifests/03_operator_trusted_ca.yaml
- manifests/04_roles.yaml
- manifests/05_serviceaccount.yaml
- manifests/07_deployment.yaml
- manifests/08_clusteroperator.yaml
- manifests/09_flowschema.yaml
This implements phase 1 of openshift/enhancements#482
> Annotate manifests for single-node-developer cluster profile

- manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
> Bug 1916949: manifests: exclude rbac resources in openshift-oauth-apiserver namespace from hosted profile

- pkg/controllers/proxyconfig/proxyconfig_controller.go
- pkg/controllers/proxyconfig/proxyconfig_controller_test.go
- pkg/controllers/proxyconfig/proxymatching.go
This fixes the naive implementation where noProxy match would only
be considered when the exact hostname of the tested endpoint
would appear in the NoProxy string. NoProxy usually defines
domains, but could also define IP ranges, neither of which
would have previously matched and false Degraded status would
be reported.
/assign @sttts
> Bug 1917114: proxyconfig controller: match URL to noproxy correctly

- test/library/gitlabidp.go
Deployment with the latest image was failing as follows:
```
waits.go:85: waiting for route e2e-test-authentication-operator-qsp8f/test-route to be admitted
waits.go:93: no admitted ingress for route test-route in namespace e2e-test-authentication-operator-qsp8f
waits.go:105: waiting for HEAD at "https://test-route-e2e-test-authentication-operator-qsp8f.apps.ci-op-znybibly-1d877.origin-ci-int-aws.dev.rhcloud.com" to report 200
waits.go:120: HEAD https://test-route-e2e-test-authentication-operator-qsp8f.apps.ci-op-znybibly-1d877.origin-ci-int-aws.dev.rhcloud.com: 503 Service Unavailable
waits.go:120: HEAD https://test-route-e2e-test-authentication-operator-qsp8f.apps.ci-op-znybibly-1d877.origin-ci-int-aws.dev.rhcloud.com: 502 Bad Gateway
gitlabidp.go:105:
Error Trace:	gitlabidp.go:105 …
```
> e2e: Pin gitlab docker image to 13.8.4-ce.0

- manifests/09_flowschema.yaml
Important Note: We support upgrade and downgrade - 4.7 to 4.6 downgrade would behave very badly (in a skew case). So we should NOT back port to 4.7
> switch to v1beta1 for the p&f APIs

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
the general rule of thumb is to wait ~5s-10s for any service behind the service network.
during that time the controllers should remove the endpoint from the pool and the applicaiton won't receive any new connections.
> extends shutdown delay duration to 10 seconds

- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
- pkg/operator/starter.go
If we configure the webhook authenticators too early during an upgrade,
we might end up with apiservers that are incapable of handling
TokenReviews. Make sure that the version of the oauth-apiserver payload
in the version getter global to the operator is current if it is set.
If it is unset, this should not be an upgrade.
/assign @deads2k
> Bug 1946540: only configure webhook authenticators when oauth-apiservers are ready during upgrade

- bindata/oauth-apiserver/deploy.yaml
- bindata/oauth-apiserver/ns.yaml
- bindata/oauth-openshift/deployment.yaml
- bindata/oauth-openshift/ns.yaml
- manifests/00_namespace.yaml
- manifests/07_deployment.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
Wrong version source was used for the oauth-apiserver version
and so the webhook authenticators would never be used on
upgraded clusters.
> Bug 1946540: fix configuring webhook authenticators on upgrade

- bindata/oauth-apiserver/deploy.yaml
- bindata/oauth-openshift/deployment.yaml
- manifests/07_deployment.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- manifests/07_deployment.yaml
This is based on the following measurements on an idle 4.8-ci cluster:
CPU:
Memory:
These values are higher than the current settings, but let me know if this increase is concerning.
/cc @sttts @stlaz
> Bug 1953041: manifests/deployment: bump cpu and memory resource requests

- go.mod
- go.sum
- pkg/controllers/common/config.go
- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
- pkg/controllers/routercerts/controller.go
- pkg/controllers/routercerts/controller_test.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/modules.txt
During e2e testing, the routing team is adding additional router which revealed that we may rollout unnecessarily as we don't particularly care about any other but the default router cert/keys.
/hold
contains fake bump on a PoC in lib-go
>  Bug 1950379: routersecret: sync only the cert/key pair for the default domain

- Makefile
- test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
We are going to move the rotation tests to a separate CI job. It will shorten the overall time needed to test encryption but also increase the pass rate of the tests as we have seen them frequently failing due to a timeout.
This PR adds only a stub so that the new CI job can be configured.
We have already split the tests for kas-o in openshift/cluster-kube-apiserver-operator#1131
> Bug 1943804: stub for splitting encryption tests

- test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
- test/e2e-encryption/encryption_test.go
The current timeout for all encryption test is 4 hours.
Previously the time needed to roll out a new KAS was 15 minutes, due to a known issue on AWS with the NLB it can take now 22 minutes.
It means that the tests need ~25 min to make sure that all servers are on the same revision and it is safe to start the test.
Since the rotation scenario needs to enable the encryption first, then wait and check if all resources were migrated, then change the encryption key and check the migration again.
It means that only these tests will need ~1 hour just for installing the servers.
Thus this PR moves the rotation tests to a separate CI job.
It will shorten the overall time needed to test encryption but also increase the pass rate of the tests as we have seen them frequently failing to due to a …
> Bug 1943804: splits the encryption tests

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
- vendor/modules.txt
Before this change, the precondition checker could run the encryption controllers when the caches haven't been synchronized.
During synchronization, the controllers send live requests to the API server.
A **single** failed request can put a controller into a degraded state and leave it in that state forever. 
Thus the precondition function MUST be called after the caches were synchronized. This PR ensures that.
For example, in [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-aws-upgrade/1400652395809083392/artifacts/e2e-aws-upgrade/) CI run the `kas-o` operator acquired a lock at `03:33:24`:
at `03:33:40` the `EncryptionPruneControllerDegraded` went degraded and **never** recovered.
around the same time, a …
> Bug 1969631: encryption controllers wait for all informers before running the sync loops

- pkg/controllers/webhooksremover/webhooksremover.go
- pkg/operator/starter.go
In 4.8, we're configuring the
authentication.spec.webhookTokenAuthenticator field. However, in 4.7,
having this field configured makes the kube-apiserver-operator
mark the cluster as "upgradable=false".
We need to unset the field in 4.7 in order to prevent a downgraded
cluster to become unupgradable.
/assign @deads2k
> [4.7] Bug 1971087: add a controller to remove webhooktokenauthenticator config

- pkg/operator/configobservation/authentication/apiaudiences.go
- pkg/operator/configobservation/authentication/apiaudiences_test.go
- pkg/operator/configobservation/configobservercontroller/config_observer_controller.go
- pkg/operator/configobservation/listers.go
- pkg/operator/starter.go
- pkg/operator/workload/sync_openshift_oauth_apiserver.go
- pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
- test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
When the kube-apiserver receives a token validation request,
that request is audience-constrained since we configure the SA
issuer and audiences. This means that kube-apiserver also checks
the audiences returned from a TokenReview during webhook token
authentication.
The oauth-apiserver by default uses the https://kubernetes.default.svc
audiences. If authentication.spec.serviceAccountIssuer is set however,
the kube-apiserver will expect different audiences from the default.
If the oauth-apiserver does not adjust the TokenReview endpoint,
users won't be able to validate their OAuthAccessTokens as the
audience returned by the oauth-apiserver in a TokenReview response
would differ
/assign @s-urbaniak
> Bug 1977054: observe api-audiences for the oauth-apiserver

- bindata/oauth-apiserver/deploy.yaml
- go.mod
- go.sum
- pkg/operator/assets/bindata.go
- pkg/operator/configobservation/configobservercontroller/config_observer_controller.go
- pkg/operator/starter.go
- pkg/operator/workload/sync_openshift_oauth_apiserver.go
- pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
- vendor/github.com/openshift/library-go/pkg/operator/csr/csr_approver.go
- vendor/modules.txt
Removes static elements of audit policy and allows for dynamic creation with groups specified.
> add dynamic audit policy controller

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/modules.txt
the condition controller is used to report the current state of the encryption: EncryptionCompleted, EncryptionInProgress or DecryptionCompleted
unfortunately, the previously set condition might have been cleared due to a bug in the controller every time the API server was deployed.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1982398
> encryption condition controller doesn't reset previously set condition

- manifests/0000_90_cluster-authentication-operator_03_prometheusrule.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1977027
This Pull Request removes the `0000_90_cluster-authentication-operator_03_prometheusrule.yaml` Prometheus Rule, which is no longer necessary after the successful upgrade.
The implementation uses the `release.openshift.io/delete: "true"` annotation, which has been described in https://github.com/openshift/cluster-version-operator/pull/438/files#diff-a094a7a19dcb006cb1206c7011aba1254ab06411b1cfcdc319a6355175132b02
> Bug 1977027: Remove not needed Prometheus Rule

- bindata/oauth-openshift/trust_distribution_role.yaml
- bindata/oauth-openshift/trust_distribution_rolebinding.yaml
- pkg/controllers/trustdistribution/trustdistribution_controller.go
- pkg/operator/assets/bindata.go
- pkg/operator/starter.go
- test/e2e/custom_route_test.go
Since the oauth-server's serving certificates can now be customized, it's important to publish the serving certificate of the server. This certificate should be used by applications like the oauth-proxy and openshift-console in order for them to be capable of successfully complete the OAuth2 authorization process as these clients eventually get to talk directly to the oauth-server and therefore need to trust it.
/assign @slaskawi 
/cc @deads2k @jhadvig @spadgett
> distribute oauth-server trust via a openshift-config-managed configmap

- pkg/operator/starter.go
Under certain circumstances, the CSR with the given name may already exist, different from what we expect. Use `GenerateName` to prevent this.
/assign @s-urbaniak
>  Bug 1978193: csr request: use generate names to prevent getting stuck waiting for a cert

- bindata/oauth-openshift/deployment.yaml
- manifests/07_deployment.yaml
- pkg/operator/assets/bindata.go
Both cluster-authentication-operator and openshift-oauth-apiserver need to run as root in order to be able to overwrite /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.
This is implied from picking the default anyuid SCC.
However, if user specifies a more restricted SCC specifying MustRunAsRange with higher or equal priority than anyuid,
that one will be picked causing both processes to be started as non-root.
This fixes it by specifying runAsUser: 0 explicitly.
Alternative: we can try to make `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` writable by all users, i.e. in the Dockerfile (?) to be able to run as non-root.
/cc @stlaz @sttts
> Bug 1973005: manifests, bindata: explicitely set runAsUser for operator and operand

- bindata/oauth-apiserver/oauth-apiserver-pdb.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/starter.go
In case master nodes are drained to quickly in a row there's no
waiting until instances go back to available. So it's possible
for two or more replicas to go unavailable which may lead
to all instances going unavailable.
Based on https://github.com/openshift/library-go/pull/1056/commits/8efd1883d406cc389eb25e2a257c4451dfbd668c
> bug  1998031: Deploy PDB to prevent more than one replica going unavailable

- bindata/oauth-apiserver/oauth-apiserver-pdb.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/starter.go
In case master nodes are drained to quickly in a row there's no
waiting until instances go back to available. So it's possible
for two or more replicas to go unavailable which may lead
to all instances going unavailable.
Backporting https://github.com/openshift/cluster-authentication-operator/pull/476
> [4.8] bug 2003946: Deploy PDB to prevent more than one replica going unavailable

- bindata/oauth-apiserver/ns.yaml
- pkg/operator/assets/bindata.go
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-oauth-apiserver` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
> podsecurity: enforce privileged for openshift-oauth-apiserver namespace

- manifests/02_config.cr.yaml
The operator config is not needed for an ibm-cloud or hypershift deployment because the auth operator does not run in cluster.
> Exclude operator config for ibm-cloud-managed profile

- pkg/operator/starter.go
Currently, only apiserver high inertia is considered but not oauthserver.
This fixes it.
/cc @stlaz @deads2k
> Bug 2019832: pkg/operator: configure high inertia for apiserver and OAuthServer

- test/library/keycloakidp.go
As described in the docs [1] and the kubernetes example [2], the
aforementioned environment variable is needed for keycloak to properly
function behind a proxy (in our case, ingress).
[1] https://hub.docker.com/r/jboss/keycloak/
[2] https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes-examples/keycloak.yaml
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> test/lib: Set `PROXY_ADDRESS_FORWARDING` for keycloak

- test/library/keycloakidp.go
the latest label (which uses 15.0.2) does not work with FIPS. So we need
to stay in 15.0.1 for now.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> test/library: Pin keycloak contianer label to 15.0.1

- pkg/controllers/oauthendpoints/oauth_endpoints_controller.go
- pkg/controllers/oauthendpoints/oauth_endpoints_controller_test.go
The endpoints checker would use hostname from the first admitted ingress but it seems that the older ingresses may still appear in the route's status.
/assign @s-urbaniak 
cc @openshift/openshift-team-auth-maintainers
> Bug 2030961: endpoints checker: check only the custom hostname if configured

- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/modules.txt
Builds on top of https://github.com/openshift/library-go/pull/1246
Also need WithIsSNOCheck from https://github.com/openshift/library-go/pull/1238
/hold
- needs https://github.com/openshift/library-go/pull/1238 to merge
- needs https://github.com/openshift/library-go/pull/1266 to merge
> bug 2039670: Create the PDB dynamically so it does not get created on the SNO topology

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- go.sum
supersedes https://github.com/openshift/cluster-authentication-operator/pull/455
> golang 1.16 bump: Updating ose-cluster-authentication-operator images to be consistent with ART

- test/library/keycloakidp.go
While the KC issue was not fixed it's more important to test with
the latest keycloak version for us. The people depending on the
test library can pin their dependency to the previous version.
> Bug 2024841: use latest keycloak for testing

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/modules.txt
To pick up https://github.com/openshift/library-go/pull/1287
> bug 2039670: Sync the library-go

- pkg/operator/starter.go
https://bugzilla.redhat.com/show_bug.cgi?id=2039417
This Pull Request removes a stale status condition that was removed from code in https://github.com/openshift/cluster-authentication-operator/commit/7c29d664bd571ce5f8e99456a206584651d200a7
> Bug 2039417: remove degraded condition 4.9

- pkg/operator/starter.go
Since counters are monotonic, their values are not reset, hence we have to use the `increase` function to detect faulty certificates. Here, a window of 30 minutes has been chosen to have a good reaction time after certs have been corrected.
/cc @stlaz
> Bug 2037274: pkg/operator#LegacyCNCerts: use increase function

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
This also uses a startup probe instead of a long initial delay seconds for livez and instead of excessive failure thresholds for readiness.  The failure thresholds were so long that the readiness check never failed.
/assign @tkashem @s-urbaniak
> make apiserver readiness probe honor readyz

- test/library/keycloakidp.go
With v18, the Keycloak configuration switch "metrics-enabled" does not
enable health endpoints any more: those are enabled with
"health-enabled". This PR fixes the tests to use this configuration
switch, as the Keycloak test-dependency is not pinned.
> e2e: Use Keycloak v18.0.0

- manifests/00_namespace.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
"objectRef": "openshift-authentication-operator/deployments/authentication-operator",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"authentication-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"authentication-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"authentication-operator\" must set …
```
> manifests: specify pod security level

- bindata/oauth-openshift/ns.yaml
- pkg/operator/assets/bindata.go
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
baseline:
Failure: pods "oauth-openshift" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volume "audit-dir"), privileged (container "oauth-openshift" must not set securityContext.privileged=true)
```
```
restricted:
Failure: pods "oauth-openshift" is forbidden: violates PodSecurity "restricted:latest": hostPath volumes (volume "audit-dir"), privileged (container "oauth-openshift" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "oauth-openshift" must set …
```
> AUTH-133: bindata/oauth-openshift: specify pod security level

- Makefile
- pkg/controllers/customroute/custom_route_conditions.go
- pkg/operator/datasync/errors.go
- pkg/operator/datasync/validation.go
- pkg/operator/datasync/validation_test.go
This patch adds a new validation check for custom route HTTPS
certificates: certificates without SAN fields will prevent upgrades.
This change puts in force the long-standing deprecation of the CN field
as a provider for names.
After this patch, custom routes secured with legacy HTTPS certificates
will prevent the upgrade to OCP v4.10. OCP v4.10 is compiled with Go
v1.17 and is incompatible with such legacy certificates; this
deprecation prevents unexpected failures to occur on upgrade.
Addresses: Bug 2052467
> Bug 2052467: Custom route HTTPS certificate SAN validation

- pkg/controllers/trustdistribution/trustdistribution_controller.go
backport of https://github.com/openshift/cluster-authentication-operator/pull/573
/assign @ibihim
> [4.11] Bug 2107028: only ever include certificates in the oauth-serving-cert CM

- pkg/controllers/common/config.go
- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
- pkg/controllers/proxyconfig/proxyconfig_controller.go
- pkg/controllers/proxyconfig/proxyconfig_controller_test.go
- pkg/controllers/routercerts/controller.go
This PR contains the following changes:
- increase check interval to 60 min
- perform the actual endpoint calls with/without proxy only when they are required to deduce the check outcome
- filter configmap events to only the ones used in the context of the proxy config checker
> AUTH-363: make proxy config check less obtrusive

- bindata/oauth-apiserver/svc.yaml
- pkg/operator/assets/bindata.go
The oauth-apiserver ServiceMonitor is not able to find the oauth-apiserver Service because the label selectors don't match causing no metrics to be collected for the apiserver.
> Correctly link oauth apiserver ServiceMonitor with its Service

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
…ycle events
used here: https://github.com/openshift/oauth-apiserver/blob/release-4.14/vendor/k8s.io/apiserver/pkg/server/config.go#L694-L725
> OCPBUGS-8093: properly set the pod name and namespace in graceful termination lifecycle events

- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
- pkg/controllers/oauthclientscontroller/oauthclientscontroller_test.go
This PR changes the input type of the `randomBits()` func to `uint` so that it won't accept any negative numbers as input (which cause a panic).
> OCPBUGS-17987: generate only >=0 number of random bits

- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
Remove "include.release.openshift.io/ibm-cloud-managed:" annotation in order to CVO not deploy the service monitor
> OCPBUGS-18115: Remove "include.release.openshift.io/ibm-cloud-managed:" annotation 

- bindata/oauth-apiserver/oauth-apiserver-pdb.yaml
- pkg/operator/assets/bindata.go
allow eviction of unhealthy (not ready) pods even if there are no disruptions allowed on a PodDisruptionBudget. This can help to drain/maintain a node and recover without a manual intervention when multiple instances of nodes or pods are misbehaving. Use this with caution, as this option can disrupt perspective pods that have not yet had a chance to become healthy.
> WRKLDS-1004: use AlwaysAllow UnhealthyPodEvictionPolicy in PDBs

- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
The apiserver_request_sli_duration_seconds metric was introduced as a
replacement of apiserver_request_slo_duration_seconds which is
deprecated in Kubernetes 1.27.
To also avoid storing duplicated data in Prometheus, we need to drop
the apiserver_request_slo_duration_seconds at the ServiceMonitor level.
> OCPBUGS-18939: manifest: drop slo latency metrics in favor of sli

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
if true the HTTP Server will continue listening until all non long running request(s) in flight have been drained,
during this window all incoming requests will be rejected with a status code 429 and a 'Retry-After' response header,
in addition 'Connection: close' response header is set in order to tear down the TCP connection when idle.
without this flag requests that arrive after the shutdown delay duration will get a network error.
which might explain failures seen in: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-upgrade/1759779765541146624
The other issue is that `TerminationMinimalShutdownDurationFinished` says `The minimal shutdown duration of 0s finished` which means that the server can be immediately …
> NO-ISSUE: oauth-apiserver: enable shutdown-send-retry-after 

- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/controllers/readiness/wellknown_ready_controller_test.go
cc @openshift/openshift-team-auth
> OCPBUGS-32089: wellknown-readiness: perform several attempts to connect before going unavailable

- bindata/oauth-apiserver/deploy.yaml
- bindata/oauth-openshift/deployment.yaml
- manifests/07_deployment.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
This is a manual cherry-pick of #656. This PR does not include the refactoring changes of bindata, instead only the required-scc changes.
> [release-4.15]  OCPBUGS-34795: set required-scc for openshift workloads

- OWNERS
Add ibihim as approver, add liouk as reviewer.
Both of us have contributed to the repository. I had the pleasure to refactor and work with the observed config to deliver an audit policy to the oauth-server.
Liouk worked on the proxy config.
> NO-JIRA: OWNERS: add ibihim, liouk, rm old

- test/library/gitlabidp.go
- test/library/idpdeployment.go
- test/library/keycloakidp.go
- vendor/k8s.io/client-go/tools/watch/informerwatcher.go
- vendor/k8s.io/client-go/tools/watch/retrywatcher.go
- vendor/k8s.io/client-go/tools/watch/until.go
- vendor/modules.txt
* run deployment instead of a pod
* ping Keycloack version to v25
* since Keycloak v25 `/health` is no longer exposed on public ports. Use deployment probes instead
> NO-JIRA: Several fixes for Keycloack IDP test

- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
Ensure all created secrets have ownership annotations
> OCPBUGS-35828: controller: set ownership annotation for webhook-auth secret

- .ci-operator.yaml
- Dockerfile.rhel7
https://github.com/openshift/cluster-authentication-operator/pull/689
> OCPBUGS-39037: Updating ose-cluster-authentication-operator-container image to be consistent with ART for 4.18

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
This PR improves the liveness/readiness checks of the oauth-apiserver.
In particular:
- set `etcd-healthcheck-timeout` and `etcd-readycheck-timeout` to 1sec less than the respective probe timeouts
- replace liveness probe path `healthz` with `livez`, and exclude `etcd` from the probe
- increase the readiness probe failure threshold to 3
- set `shutdown-delay-duration` to 50s; the kubelet won't wait for another period if the previous probe fails (see note below), so if `timeoutSeconds > periodSeconds` it'll fire the subsequent probes immediately, therefore worst case is `5s + 3*10s + 15s (buffer)`
- set `terminationGracePeriodSeconds` to 120s: non-long-running requests timeout (60s) + shutdown delay (50s) + 10s buffer
Note (thanks @benluddy): the probes are implemented using a ticker, …
> OCPBUGS-41586: increase oauth-apiserver failureThreshold

- go.mod
- test/e2e/external_oidc_test.go
- test/e2e/keycloak_test.go
- test/library/gitlabidp.go
- test/library/idpdeployment.go
- test/library/keycloakidp.go
- test/library/waits.go
- vendor/github.com/openshift/api/features/features.go
- vendor/github.com/openshift/api/features/util.go
- vendor/modules.txt
This PR adds an e2e test for the direct external OIDC authentication type (BYO-OIDC). It requires the `ExternalOIDC` feature gate to be enabled.
Currently, the e2e works as follows:
- deploy keycloak in the cluster, to use as an OIDC provider
- configure the OIDC as a direct provider in the KAS
- update the authentication CR with the oidc provider configuration
- sync the oidc provider's CA, if necessary, to the KAS pods static resources
- patch the cluster proxy and the KAS CLI args to provide the OIDC configuration
- wait for the changes to get rolled out
- run some basic keycloak sanity checks
- run some baseline authentication checks via the KAS
The goal of this test is to incrementally add more test cases, as development of the external OIDC feature progresses. Some upcoming TODOs:
- …
> AUTH-546: Direct external OIDC e2e test

- Dockerfile.rhel7
Allow this ARG to be overriden by builds so that OKD builds may have the correct branding by default. OKD/SCOS builds pass the build-arg TAGS=scos so pkg/controllers/configobservation/oauth/brand_okd.go which has //go:build !ocp will be built instead of pkg/controllers/configobservation/oauth/brand_ocp.go which has //go:build ocp. This change should not affect the OCP build of the operator image.
> OKD-226: Dockerfile.rhel7: Add ARG TAGS=ocp

- manifests/09_flowschema.yaml
bump flowcontrol v1beta3 to v1
looking for sources of:
```
I1003 15:59:34.909915 109482 api_requests.go:76] api flowschemas.v1beta3.flowcontrol.apiserver.k8s.io, removed in release 1.32, was accessed 18 times
I1003 15:59:34.909991 109482 api_requests.go:76] api prioritylevelconfigurations.v1beta3.flowcontrol.apiserver.k8s.io, removed in release 1.32, was accessed 9 times
I1003 15:59:34.910022 109482 api_requests.go:125] user/system:serviceaccount:openshift-cluster-version:default accessed flowschemas.v1beta3.flowcontrol.apiserver.k8s.io 18 times
[FAILED] in [It] - github.com/openshift/origin/test/extended/apiserver/api_requests.go:134 @ 10/03/24 15:59:34.91
• [FAILED] [0.500 seconds]
[sig-arch][Late] [It] clients should not use APIs that are removed in upcoming releases …
```
> OCPBUGS-42745: manifests should not use APIs that are removed in upcoming releases

- pkg/controllers/common/conditions.go
- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/operator/starter.go
Compared **e2e-operator** job from https://github.com/openshift/cluster-authentication-operator/pull/709 with the same job from this PR:
> API-1835: Migrate WellKnownReadyController to SSA

- manifests/08_clusteroperator.yaml
The CVO pre-creates the relatedresoruces in status.  if the operator fails to run for some reason, this ensures we get some basic collection.  I pulled these values from a successful CI run.
/assign @liouk @ibihim
> NO-JIRA: add relatedResources to authentication for collection if operator crashes

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/manifestclient/context.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/group_resource_discovery.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/list.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/modules.txt
From failed run: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-4.18-cpou-upgrade-from-4.15-aws-ipi-mini-perm-arm-f14/1842004955238502400
noteworthy log message:
```
2024-10-04T10:05:42.236079365Z E1004 10:05:42.236012       1 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
2024-10-04T10:05:42.236079365Z goroutine 2202 [running]:
2024-10-04T10:05:42.236079365Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x26081a0, 0x3005130})
2024-10-04T10:05:42.236079365Z 	/go/src/github.com/openshift/cluster-authentication-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
2024-10-04T10:05:42.236079365Z …
```
> OCPBUGS-42932: ensure annotations map exists before mutating it

- go.mod
- go.sum
- pkg/operator/replacement_starter.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/readwrite_roundtripper.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/managementstatecontroller/management_state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
- vendor/modules.txt
> API-1835: Bump library-go to get SSA in multiple controllers

- go.mod
- go.sum
- pkg/cmd/mom/apply_configuration_command.go
- pkg/cmd/mom/output_resources_command.go
- pkg/operator/replacement_starter.go
- pkg/operator/starter.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/apply_configuration.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/client_mutations.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/command.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_apply_configuration.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/directory_mutations.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/equivalence.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/operator_launch_helpers.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/options.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/easy_creation.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/types.go
- vendor/modules.txt
this allows us to keep updating the MOM
> API-1835: name all the runone functions

- pkg/controllers/externaloidc/externaloidc_controller.go
- pkg/controllers/externaloidc/externaloidc_controller_test.go
- pkg/operator/replacement_starter.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
- vendor/modules.txt
This PR adds a controller behind the `ExternalOIDC` feature gate that tracks the auth CR, and when auth type is configured to be OIDC, it:
- creates a structured auth config object based on the auth CR and validates it
- serializes it into JSON and stores it into a configmap
- syncs that configmap into `openshift-config-managed`, where it will be picked up by the KAS-o and synced into a static file and passed on to the KAS pods
KAS-o counterpart PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1760
Enhancement: https://github.com/openshift/enhancements/pull/1632
> AUTH-541: OIDC structured auth config

- pkg/operator/replacement_starter.go
- pkg/operator/starter.go
- test-data/apply-configuration/overall/minimal-cluster/expected-output/controller-results.yaml
updatedinitialization to parameterize feature gate accessor to allow mom to call the binary in CI
updated test to include OIDC check
> OCPBUGS-51981: fix: update starter path to account for mom integration

- test/library/keycloakidp.go
This PR investigates improvements that can be done to the Keycloak deployment to fix intermittent issues we have been having.
Improvements
- start Keycloak in development mode, which uses a local cache instead of a distributed one (see [here](https://www.keycloak.org/server/configuration#_starting_keycloak_in_development_mode) for more details)
> NO-JIRA: Keycloak e2e test improvements

- pkg/controllers/readiness/unsupported_override.go
bumped ocp/api to pull in DualReplica control plane topology type, minimum count for masters is 2 under DualReplica
> OCPEDGE-1510: feat: add minimum count for DualReplica

- pkg/controllers/configobservation/oauth/idp_conversions.go
- pkg/controllers/configobservation/oauth/idp_conversions_test.go
~~If we encounter an OIDC server which is not properly responding using JSON, we should occasionally retry pinging it for the purpose of checking password grant support rather than assuming that it doesn't support password grant forever.~~
Now: Reject and don't cache 5xx errors outright while checking for password grant support.
> OCPBUGS-59909: Don't cache server errors when checking for password grant support

- bindata/oauth-openshift/deployment.yaml
- pkg/controllers/deployment/deployment_controller.go
- pkg/controllers/deployment/deployment_controller_test.go
This PR configures the upgrade parameters according to the size of the control plane. This also ensures that during the event of an unhealthy node, the rolling upgrade can proceed.
> OCPBUGS-57444: set appropriate rolling update settings
