- manifests/0000_09_cluster-osin-operator_06_authentication_crd.yaml
- manifests/0000_09_cluster-osin-operator_07_oauth_crd.yaml
- manifests/0000_09_cluster-osin-operator_08_authentication_cr.yaml
- manifests/0000_09_cluster-osin-operator_09_oauth_cr.yaml
This PR adds the authentication and oauth CRDs
@enj is this what you'll need? or no CRs?
> add auth oauth resources to manifests

- manifests/0000_09_cluster-osin-operator_05_deploy.yaml
- manifests/image-references
> Update image references to use cluster-authentication-operator

- pkg/operator2/operator.go
- pkg/operator2/secret.go
- pkg/operator2/secret_test.go
@enj this PR adds validation for session secrets
> validate session secrets

- pkg/operator2/deployment.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/service.go
> Fix service and container port

- pkg/operator2/starter.go
@openshift/sig-auth this takes the simplest approach to getting these default custom resources created.
> Ensure default custom resources exist for top level config

- README.md
> New build?

- pkg/operator2/operator.go
The console CRD/CR does not exist yet.
> Prevent deadlock on console config

- pkg/operator2/configsync.go
- pkg/operator2/deployment.go
- pkg/operator2/idp.go
- pkg/operator2/oauth.go
Add syncing of template's secrets from the top level config
I accidentally built it on top https://github.com/openshift/cluster-authentication-operator/pull/56 when I did not check the git branch I'm on, I can split it if required.
> Sync template secrets

- manifests/cluster-authentication-operator_03_version-mapping.yaml
- manifests/cluster-authentication-operator_05_deploy.yaml
- manifests/cluster-authentication-operator_06_clusteroperator.yaml
- pkg/operator2/auth.go
- pkg/operator2/configmap.go
- pkg/operator2/deployment.go
- pkg/operator2/operator.go
- pkg/operator2/starter.go
- pkg/operator2/status.go
This will block the installation until we report availability
> Improve status handling

- pkg/operator2/ca.go
- pkg/operator2/configsync.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/secret.go
Adds more verbose error messages so that we know where the errors
we encounter come from
> Improve error messages

- pkg/operator2/deployment.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/status.go
See comment in handleVersion.
@openshift/sig-auth 
/assign @stlaz @sallyom
> Check osin deployment availability after other checks

- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
- manifests/02_service.yaml
- manifests/03_configmap.yaml
- manifests/04_roles.yaml
- manifests/05_serviceaccount.yaml
- manifests/06_deployment.yaml
- pkg/operator2/ca.go
- pkg/operator2/configsync.go
- pkg/operator2/deployment.go
- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/secret.go
- pkg/operator2/starter.go
- pkg/version/version.go
Remove "openshift-" prefix from the resource names for auth components
> bug 1700903: standardize resource names

- README.md
Probably looks a bit better than just being empty.
> README: add steps for simple test IdP config

- pkg/operator2/deployment.go
> Bug 1692290: Sort RVs before hashing them

- pkg/operator2/route.go
The OAuth server is only available at one host - the one provided by the default ingress controller.
Bug 1703504
> Bug 1703504: Get route host from status

- pkg/operator2/deployment.go
> Bug 1707049: Use TerminationMessageFallbackToLogsOnError for OAuth server

- hack/verify-govet.sh
- pkg/doc.go
- pkg/operator2/idp.go
- tools/doc.go
> Make hack scripts work with go 1.12

- Dockerfile
- Dockerfile.rhel7
- pkg/operator2/oauthclients.go
- pkg/operator2/operator.go
Small update to #138 
https://github.com/openshift/cluster-authentication-operator/compare/c45b991e34ce85b8163a7164c88f0eb1e5016194..3b444f140a2f604e0f673df25866fe2c17a9afcb
> Bootstrap OAuth clients

- manifests/07_deployment.yaml
- manifests/image-references
- pkg/operator2/deployment.go
/cc @deads2k @tnozicka 
Depends on:
https://github.com/openshift/release/pull/4215
https://github.com/openshift/origin/pull/23283
> Migrate from hypershift to oauth-server image

- glide.lock
- pkg/operator2/apiserver.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- vendor/github.com/openshift/api/config/v1/types_apiserver.go
- vendor/github.com/openshift/api/config/v1/types_infrastructure.go
- vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
- vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/api/operator/v1/doc.go
- vendor/github.com/openshift/library-go/glide.lock
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
- vendor/golang.org/x/tools/cmd/present/static/notes.js
- vendor/golang.org/x/tools/internal/imports/fix.go
- vendor/golang.org/x/tools/internal/lsp/lsp_test.go
- vendor/golang.org/x/tools/internal/lsp/source/rename.go
- vendor/golang.org/x/tools/internal/lsp/source/signature_help.go
- vendor/golang.org/x/tools/internal/lsp/source/source_test.go
- vendor/golang.org/x/tools/internal/lsp/testdata/rename/a/random.go.golden
- vendor/golang.org/x/tools/internal/lsp/testdata/rename/a/random.go.in
- vendor/golang.org/x/tools/internal/lsp/testdata/signature/signature.go
- vendor/golang.org/x/tools/internal/lsp/tests/tests.go
@stlaz we need validation for the APIServer config to make sure each value is a valid regex.
> Honor CORS set via APIServer config

- pkg/operator2/operator.go
- pkg/operator2/route.go
- pkg/operator2/status.go
> Bug 1740363: Use specific reasons for all route degraded errors

- pkg/operator2/route.go
- pkg/operator2/route_test.go
Pushing what I have initially while looking into adding tests.
> Bug 1707905: Update route when ingress domain changes

- manifests/07_deployment.yaml
> Bug 1751147: operator: fix typo to get injected with proxy env vars

- pkg/operator2/operator.go
> Inline constants so David does not die

- bindata/oauth-openshift/deployment.yaml
- pkg/operator2/assets/bindata.go
> fix trust-bundle destination

- pkg/operator2/deployment.go
> redeploy on config changes

- pkg/operator2/operator.go
- pkg/operator2/starter.go
> Bug 1798946: react to changes of the kube-system/kubeadmin secret

- pkg/operator2/starter.go
> Bug 1794311: Set namespace for route from related objects

- pkg/operator2/starter.go
Follow up to https://github.com/openshift/cluster-authentication-operator/pull/258 I missed the service :/ 
/assign @stlaz
> Bug 1794311: Set namespace for service from related objects

- pkg/operator2/deployment.go
When a pod is marked deleted, endpoints are updated instantly and
propagate to load balancers, routers, and nodes. A component that
wishes to remain available during upgrades must wait longer than
the default propagation interval for these changes to avoid having
requests delivered to pods that are shutting down.
Change the oauth server to wait 25s before terminating the serving
process and up to 40s on the node to ensure all front ends have
time to drain. The minimum interval here is how long an average
connection can take behind the router to drain, once new connections
stop getting created. I.e.
wait = time to propagate endpoints (5s) +
time for router reload (5s) +
time for longest request to finish (15s)
= 25s
> Bug 1824167: The oauth server should wait until it is out of rotation to shut down

- pkg/controller/ingressstate/ingress_state_controller.go
- pkg/controller/ingressstate/ingress_state_controller_test.go
- pkg/operator2/oauth.go
- pkg/operator2/operator.go
- pkg/operator2/status.go
Cherry-pick of #269. The cherrypick bot was unable to apply the change cleanly, as manual merging was required.
> Bug 1823622:  [release-4.4]  Fix ingress state condition flapping

- bindata/oauth-openshift/deployment.yaml
- pkg/operator2/assets/bindata.go
- test/e2e/templates_test.go
fallout of a recent refactoring
/cc @vareti @marun
> Bug 1852312: fix template mounting to the oauth-server pods

- pkg/controllers/metadata/metadata_controller.go
- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/operator2/operator.go
> remove well-known readiness duplicated code + other cosmetic fixes

- test/e2e-encryption/encryption_test.go
this PR requires https://github.com/openshift/cluster-openshift-apiserver-operator/pull/348 to be merged first.
> enables the encryption tests

- pkg/controllers/configobservation/oauth/idp_conversions.go
> Bug 1861789: improve password-grant discovery message on non-JSON server response

- go.mod
- go.sum
- pkg/controllers/configobservation/configobservercontroller/observe_config_controller.go
- pkg/controllers/configobservation/oauth/observe_idps.go
- pkg/operator/configobservation/config_observer_controller.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
- vendor/modules.txt
let's use this PR to also pull the below lib-go fix so that the BZ is verifiable:
- https://github.com/openshift/library-go/pull/861
/hold
contains fake bump
> Bug 1777137: don't post new observed config on resources validation

- pkg/controllers/targetversion/target_version_controller.go
- pkg/operator/starter.go
> Bug 1859591: version controller: honor system CA bundle when checking route health

- pkg/controllers/deployment/deployment_controller.go
Deployment controller was possibly constantly updating the observed generation and replica count. Moreover, it was not protected to conflict errors from the peer controllers.
> Bug 1870565: deployment: avoid degraded due to conflict error

- manifests/09_flowschema.yaml
- `SAR` or `tokenreviews` from oauth 
- Any other requests from oauth server.
- Traffic from oauth operator.
See https://github.com/openshift/cluster-kube-apiserver-operator/pull/966 for more details.
> flowschema for oauth server and its operator

- go.mod
- go.sum
- vendor/modules.txt
A clean up PR to remove unused dependency
> remove unused vbom.ml/util dependency

- manifests/09_flowschema.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- pkg/operator/starter.go
@deads2k @stlaz we pass a wrong lister to `NewIngressNodesAvailableController` which ONLY include operator config resources that match field selector "meta.name=cluster". This won't work for "ingress" config that has name "default"....
> Bug 1893386: Fix wrong operator config informer

- go.mod
- pkg/controllers/proxyconfig/proxyconfig_controller.go
- pkg/controllers/proxyconfig/proxyconfig_controller_test.go
- pkg/operator/starter.go
- vendor/golang.org/x/net/http/httpproxy/proxy.go
- vendor/modules.txt
This is an attempt to address https://issues.redhat.com/browse/MSTR-1011
Adds a new controller to report degraded conditions when the proxy is misconfigured.
> Add a controller to report misconfigured proxy

- pkg/controllers/payload/payload_config_controller.go
Also removes duplicate code
/assign @vareti
> oauthserver: grab unsupported overrides from a prefixed tree

- manifests/0000_90_cluster-authentication-operator_01_prometheusrbac.yaml
- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
- manifests/00_namespace.yaml
- manifests/02_config.cr.yaml
- manifests/02_service.yaml
- manifests/03_configmap.yaml
- manifests/03_openshift_service_ca.yaml
- manifests/03_operator_trusted_ca.yaml
- manifests/04_roles.yaml
- manifests/05_serviceaccount.yaml
- manifests/09_flowschema.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
> Add IBM Cloud managed annotations to CVO manifests

- bindata/oauth-apiserver/RBAC/useroauthaccesstokens_binding.yaml
- bindata/oauth-apiserver/RBAC/useroauthaccesstokens_clusterrole.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/starter.go
> add RBAC for the new useroauthaccesstokens

- pkg/controllers/proxyconfig/proxyconfig_controller.go
- pkg/operator/starter.go
> Bug 1901057: proxyconfig controller: add router CA to the trusted pool

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
The number is arbitrary, modify if it proves wrong.
> Bug 1905329: oauth-apiserver deployment: add cpu and memory requests

- pkg/controllers/deployment/deployment_controller.go
This could cause panics in a rare case where the resource cannot be
found
/assign @sttts
> Bug 1921275: deploymentController: treat error retrieving authentication.operator/cluster

- pkg/operator/starter.go
> Remove the 'authentication.operator.openshift.io/managed' annotation from user,oauth apiservices

- bindata/oauth-apiserver/authenticator-clusterrole.yaml
- bindata/oauth-apiserver/authenticator-clusterrolebinding.yaml
- bindata/oauth-apiserver/authenticator-kubeconfig.yaml
- bindata/oauth-apiserver/authenticator-sa.yaml
- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
- pkg/operator/assets/bindata.go
- pkg/operator/starter.go
- pkg/operator/workload/sync_openshift_oauth_apiserver.go
- pkg/operator/workload/sync_openshift_oauth_apiserver_test.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
Depends on #243 
Untested and probably broken, submitting to see what CI thinks
> wire openshift authentication as a webhook authenticator

- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
> Bug 1934107: webhook authentication: fix oauth-apiserver IP for IPv6 environments

- pkg/controllers/proxyconfig/proxyconfig_controller.go
- pkg/libs/endpointaccessible/endpoint_accessible_controller.go
> Bug 1954544: endpoints controller: actually use the context-constrained request

- pkg/controllers/common/conditions.go
- pkg/controllers/common/conditions_test.go
- pkg/controllers/readiness/wellknown_ready_controller.go
> Bug 1939580: wellknownready: delay going degraded on oauthmetadata changes

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/controller/factory/eventfilters.go
- vendor/github.com/openshift/library-go/pkg/operator/csr/csr_approver.go
- vendor/modules.txt
> Bug 1965929: bump lib-go to get improved performance for the CSR approver

- manifests/0000_90_cluster-authentication-operator_02_servicemonitor.yaml
> Bug 1986829: metrics: use client cert auth for metrics scraping

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apigroup.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/k8s.io/client-go/restmapper/category_expansion.go
- vendor/k8s.io/client-go/restmapper/discovery.go
- vendor/k8s.io/client-go/restmapper/shortcut.go
- vendor/modules.txt
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1979303 and https://bugzilla.redhat.com/show_bug.cgi?id=1982398
> Bug 1979303: clear encryption conditions when there is no work to be done

- pkg/operator/starter.go
> Bug 1988576: pkg/operator: Add deprecated stale status

- pkg/libs/endpointaccessible/endpoint_accessible_controller.go
> typo fix: enpoints -> endpoints

- pkg/operator/starter.go
> pkg/operator: set high inertia for all topologies except SingleReplica

- pkg/libs/endpointaccessible/endpoint_accessible_controller.go
This turns message like:
`Operator unavailable (OAuthServerRouteEndpointAccessibleController_EndpointUnavailable): OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org/healthz": dial tcp: lookup oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org on 172.30.0.10:53: no such host`
to:
`Operator unavailable (OAuthServerRouteEndpointAccessibleController_EndpointUnavailable): OAuthServerRouteEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org/healthz": dial tcp: lookup oauth-openshift.apps.ci-op-6izkt7mz-16f7c.gcp-2.ci.openshift.org on 172.30.0.10:53: no such host (this is likely result of malfunctioning DNS server)`
> Bug 1996647: endpointsaccessible: clarify degraded message when DNS is broken

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/modules.txt
Library go bump to delete managed fields
> bug 2042038: bump library go

- pkg/operator/starter.go
Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>
> bug 2040521: routeName used as customSecretName

- pkg/controllers/customroute/custom_route_controller.go
- pkg/controllers/ingressnodesavailable/ingress_nodes_available_controller.go
- pkg/controllers/ingressstate/ingress_state_controller.go
- pkg/controllers/metadata/metadata_controller.go
- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
- pkg/controllers/payload/payload_config_controller.go
- pkg/controllers/readiness/wellknown_ready_controller.go
- pkg/controllers/routercerts/controller.go
- pkg/controllers/serviceca/service_ca_controller.go
- pkg/controllers/trustdistribution/trustdistribution_controller.go
- pkg/controllers/webhookauthenticator/webhookauthenticator_controller.go
- pkg/libs/endpointaccessible/endpoint_accessible_controller.go
https://bugzilla.redhat.com/show_bug.cgi?id=1958198
> Bug 1958198: Avoid zero or low resync intervals

- pkg/controllers/trustdistribution/trustdistribution_controller.go
> Bug 2078287: only ever include certificates in the oauth-serving-cert CM

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- go.sum
> Updating ose-cluster-authentication-operator images to be consistent with ART

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- pkg/controllers/common/conditions.go
- pkg/controllers/metadata/metadata_controller.go
- pkg/operator/assets/bindata.go
supersedes https://github.com/openshift/cluster-authentication-operator/pull/595
> [4.13] OCPBUGS-6189: art image update

- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
Saw https://github.com/openshift/cluster-authentication-operator/pull/608/files has a line of OC change. Adding the new OC as well.
CC @liouk @stlaz could you help review?
> Add openshift-cli-client in NamesFilter

- bindata/oauth-apiserver/deploy.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/workload/testdata/sync_ds_scenario_1.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_2.yaml
- pkg/operator/workload/testdata/sync_ds_scenario_3.yaml
by passing `enable-priority-and-fairness=false`
> NO-ISSUE: oauth-apiserver: disable priority and fairness

- test/library/idpdeployment.go
Hopefully this fixes:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-authentication-operator/658/pull-ci-openshift-cluster-authentication-operator-master-e2e-operator/1768183151902855168
> NO-JIRA: test/lib: create SA on deploy

- test/library/keycloakidp.go
> NO-JIRA: e2e Keycloak: retry logging in as admin

- pkg/libs/endpointaccessible/endpoint_accessible_controller_test.go
- test/library/gitlabidp.go
- test/library/idpdeployment.go
- test/library/keycloakidp.go
- vendor/k8s.io/client-go/tools/watch/informerwatcher.go
- vendor/k8s.io/client-go/tools/watch/retrywatcher.go
- vendor/k8s.io/client-go/tools/watch/until.go
- vendor/modules.txt
This is a manual cherry-pick of the following PRs:
- #679
- #680
Both are needed at the same time as both fix required tests (#679 fixes `e2e-operator`, #680 fixes `unit`).
> [release-4.16] NO-JIRA: Fixes for Keycloack IDP test and unit tests

- Dockerfile.rhel7
test with https://github.com/openshift/api/pull/2030
> create CRDs from openshift/api

- cmd/authentication-operator/main.go
- go.mod
- go.sum
- pkg/cmd/mom/apply_configuration_command.go
- pkg/cmd/mom/output_resources_command.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_directory_reader.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/mutation_tracker.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/serialized_request.go
- vendor/github.com/openshift/library-go/pkg/manifestclient/write_roundtripper.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryapplyconfiguration/options.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/command.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/options.go
- vendor/github.com/openshift/multi-operator-manager/pkg/library/libraryoutputresources/types.go
- vendor/modules.txt
now possible to properly merge.
> API-1835: adds `output-resources` to cluster-authentication operator.

- pkg/operator/replacement_starter.go
xref: https://github.com/openshift/library-go/pull/1857
> API-1835: use manifestclient.RecommendedRESTConfig()

- OWNERS
Adds @liouk as approver, removes @deads2k.
> NO-JIRA: OWNERS: update approvers

- pkg/controllers/oauthclientscontroller/oauthclientscontroller.go
- pkg/controllers/oauthclientscontroller/oauthclientscontroller_test.go
[OCPBUGS-48176](https://issues.redhat.com/browse/OCPBUGS-48176)
Changing the way we create OAuth clients - now the code first checks if the OAuth client already exists. If it exists, it updates the client only when needed. This stops the repeated "AlreadyExists" (409) errors in the logs.
- Review the changes
- Provision a cluster for this pr
- Check the audit logs and confirm that you do not see repeated 409 errors for OAuth clients
```
oc adm node-logs ip-10-0-108-43.us-east-2.compute.internal --path=oauth-apiserver/audit.log | grep '"code":409' | grep 'openshift-authentication-operator'
```
- Confirm that scaling the operator deployment does not trigger extra 409 errors
> OCPBUGS-48176: Avoid duplicate OAuth client creation

- test/e2e-oidc/external_oidc_test.go
While running rehearsals in the scope of https://github.com/openshift/release/pull/65561, an issue with the test preconditions check was identified, where the check happened too quickly after a change and did not allow enough time for the preconditions to get fulfilled.
This PR introduces a short polling for the preconditions and will thus allow the operators to stabilize before checking.
> CNTRLPLANE-939: test/e2e-oidc: poll test preconditions for a short time instead of checking once
